#!/usr/bin/env bash
#
# canonical-id-closure-test.sh — BL-025-h regression test for
# validate-dry-run.sh Check c (canonical-id closure).
#
# PURPOSE: Lock the success path of Check c so that a regression
#          (e.g., the check returning 0 unconditionally, the meta-id
#          filter being broadened too far, or the closure scan being
#          dropped altogether) fails this test loudly.
#
# WHY: The live step corpus today contains exactly one [CANONICAL: id]
#      occurrence — the meta-id `id` at step-01:58 — which is filtered
#      by Check c's meta-id skip. Without this fixture test, Check c's
#      success path is unverified: an orphan introduced by future steps
#      (BL-025-h.1+ adds real markers) would slip through silently.
#
# Scenarios exercised against validate-dry-run.sh:
#   1. NEGATIVE — planted [CANONICAL: __not_in_contract_hash_8923__]
#      MUST fire `canonical-id-orphan` on stderr and exit non-zero.
#   2. POSITIVE — planted [CANONICAL: triage-criteria] (a real id from
#      contract.canonical_ids) MUST NOT fire `canonical-id-orphan`.
#      (Other unrelated checks may still fire — this assertion is
#      narrow to Check c's own violation category.)
#   3. POSITIVE [FILE: ...] — planted [FILE: F16-architecture.md] (a
#      real basename in contract.layout.spec_files) MUST NOT fire
#      `canonical-id-orphan` (validate-dry-run.sh Check c is scoped
#      to [CANONICAL: ...] only — this scenario asserts that the
#      [FILE: ...] marker doesn't accidentally trip Check c via a
#      sloppy regex). BL-025-h.1 acceptance criterion.
#
# Test isolation: each scenario builds an isolated tempdir steps tree
# whose only [CANONICAL: ...] reference is the planted one — no
# accidental orphans from real step files leak into the assertion.
# A stub prompts-built dir is used so Check b passes; the real spec
# dir is used so Checks d/e behave normally (they are not the focus).
#
# Exit codes:
#   0 — all scenarios pass
#   1 — at least one scenario failed
#   2 — driver error (missing dependency, fixture, etc.)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VALIDATE="${SCRIPT_DIR}/validate-dry-run.sh"

# SPEC_DIR resolution: validate-dry-run requires a real platform-contract.yaml
# and a spec corpus that passes vocabulary-audit (Check e). The juntospec
# repo lives as a sibling of juntogen in the OpenJunto topology — from
# this script (juntogen/claude/validation/scripts) the org root is 4 levels up.
# Allow OJ_SPEC_DIR env override for callers running from elsewhere.
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"
SPEC_DIR="${OJ_SPEC_DIR:-${REPO_ROOT}/juntospec}"
STEPS_DIR_REAL="${REPO_ROOT}/juntogen/claude/steps"

if [ -t 1 ]; then
    RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
else
    RED=''; GREEN=''; YELLOW=''; CYAN=''; NC=''
fi

[ -x "${VALIDATE}" ]        || { echo -e "${RED}ERROR${NC} validate-dry-run.sh missing/not executable: ${VALIDATE}" >&2; exit 2; }
[ -d "${SPEC_DIR}" ]        || { echo -e "${RED}ERROR${NC} SPEC_DIR not found: ${SPEC_DIR}" >&2; exit 2; }
[ -d "${STEPS_DIR_REAL}" ]  || { echo -e "${RED}ERROR${NC} real steps dir not found: ${STEPS_DIR_REAL}" >&2; exit 2; }

PASS_COUNT=0
FAIL_COUNT=0

# Build an isolated steps tree containing exactly one synthetic step file
# with the planted [CANONICAL: ...] marker. Returns the tempdir on stdout.
make_isolated_steps_tree() {
    local marker_id="$1"
    local td
    td=$(mktemp -d -t canonical-closure-XXXXXX)
    cat >"${td}/step-99-fixture.md" <<EOF
# Synthetic fixture step for canonical-id-closure-test

This file is generated by canonical-id-closure-test.sh and contains
exactly one canonical reference for the test scenario:

  [CANONICAL: ${marker_id}]

No other content; nothing else should be parsed by Check c.
EOF
    printf '%s' "${td}"
}

# Build a stub prompts-built dir containing a single resolved prompt
# free of unresolved placeholders so Check b passes.
make_stub_prompt_dir() {
    local td
    td=$(mktemp -d -t canonical-closure-prompt-XXXXXX)
    # Trivial built prompt — no /path/to/* placeholders, no {OJ_SOURCE}.
    cat >"${td}/step-99-fixture.prompt" <<'EOF'
This is a stub built prompt with no placeholders.
EOF
    printf '%s' "${td}"
}

run_negative_scenario() {
    local steps_td prompt_td stderr_log exit_code=0
    steps_td=$(make_isolated_steps_tree "__not_in_contract_hash_8923__")
    prompt_td=$(make_stub_prompt_dir)
    stderr_log=$(mktemp -t canonical-closure-stderr-XXXXXX)

    "${VALIDATE}" \
        --prompt-dir "${prompt_td}" \
        --spec-dir "${SPEC_DIR}" \
        --steps-dir "${steps_td}" \
        --oj-source-provided 0 \
        >/dev/null 2>"${stderr_log}" || exit_code=$?

    local stderr_text
    stderr_text=$(cat "${stderr_log}")

    local errors=""
    if [ "${exit_code}" -eq 0 ]; then
        errors="${errors}    expected non-zero exit (orphan should fire), got 0"$'\n'
    fi
    if ! printf '%s' "${stderr_text}" | grep -qF -- "canonical-id-orphan"; then
        errors="${errors}    stderr missing required substring: canonical-id-orphan"$'\n'
    fi
    if ! printf '%s' "${stderr_text}" | grep -qF -- "__not_in_contract_hash_8923__"; then
        errors="${errors}    stderr missing planted id: __not_in_contract_hash_8923__"$'\n'
    fi

    if [ -z "${errors}" ]; then
        echo -e "${GREEN}PASS${NC} negative/orphan-marker (planted '__not_in_contract_hash_8923__' fired canonical-id-orphan)"
        PASS_COUNT=$((PASS_COUNT + 1))
    else
        echo -e "${RED}FAIL${NC} negative/orphan-marker"
        printf '%s' "${errors}"
        echo -e "${CYAN}    actual exit=${exit_code}${NC}"
        echo -e "${CYAN}    actual stderr (head -40):${NC}"
        printf '%s\n' "${stderr_text}" | head -40 | sed 's/^/      /'
        FAIL_COUNT=$((FAIL_COUNT + 1))
    fi

    rm -rf "${steps_td}" "${prompt_td}" "${stderr_log}"
}

run_positive_scenario() {
    local steps_td prompt_td stderr_log exit_code=0
    # `triage-criteria` is a real id in juntospec/platform-contract.yaml.
    steps_td=$(make_isolated_steps_tree "triage-criteria")
    prompt_td=$(make_stub_prompt_dir)
    stderr_log=$(mktemp -t canonical-closure-stderr-XXXXXX)

    "${VALIDATE}" \
        --prompt-dir "${prompt_td}" \
        --spec-dir "${SPEC_DIR}" \
        --steps-dir "${steps_td}" \
        --oj-source-provided 0 \
        >/dev/null 2>"${stderr_log}" || exit_code=$?

    local stderr_text
    stderr_text=$(cat "${stderr_log}")

    # Narrow assertion: Check c's category must NOT appear for the planted
    # id. Other validators (Checks d, e) may surface unrelated violations
    # outside the scope of this regression test, so we don't assert on
    # global exit code — only on the absence of canonical-id-orphan for
    # `triage-criteria`.
    local errors=""
    if printf '%s' "${stderr_text}" | grep -E "canonical-id-orphan.*triage-criteria" >/dev/null 2>&1; then
        errors="${errors}    stderr contains canonical-id-orphan for 'triage-criteria' — but this id IS in contract.canonical_ids"$'\n'
    fi

    if [ -z "${errors}" ]; then
        echo -e "${GREEN}PASS${NC} positive/no-orphan (planted 'triage-criteria' did NOT fire canonical-id-orphan)"
        PASS_COUNT=$((PASS_COUNT + 1))
    else
        echo -e "${RED}FAIL${NC} positive/no-orphan"
        printf '%s' "${errors}"
        echo -e "${CYAN}    actual exit=${exit_code}${NC}"
        echo -e "${CYAN}    actual stderr (head -40):${NC}"
        printf '%s\n' "${stderr_text}" | head -40 | sed 's/^/      /'
        FAIL_COUNT=$((FAIL_COUNT + 1))
    fi

    rm -rf "${steps_td}" "${prompt_td}" "${stderr_log}"
}

run_positive_file_marker_scenario() {
    # BL-025-h.1: an isolated steps tree planted with a [FILE: ...] marker
    # carrying a real basename from contract.layout.spec_files MUST NOT
    # cause validate-dry-run.sh to surface a `canonical-id-orphan`
    # violation. Check c's regex is scoped to `\[CANONICAL:[ ]*...\]`,
    # so [FILE: ...] should be invisible to it. This scenario locks
    # that scope so a future broadening of Check c's regex (e.g., to
    # cover [FILE: ...] markers) without parallel handling fails the test.
    local steps_td prompt_td stderr_log exit_code=0
    steps_td=$(mktemp -d -t canonical-closure-file-XXXXXX)
    cat >"${steps_td}/step-99-fixture.md" <<'EOF'
# Synthetic fixture step for canonical-id-closure-test (file-marker scenario).

This file is generated by canonical-id-closure-test.sh and contains
a [FILE: F16-architecture.md] marker. Check c must NOT report it as
an orphan canonical-id (it is a different marker class).
EOF
    prompt_td=$(make_stub_prompt_dir)
    stderr_log=$(mktemp -t canonical-closure-stderr-XXXXXX)

    "${VALIDATE}" \
        --prompt-dir "${prompt_td}" \
        --spec-dir "${SPEC_DIR}" \
        --steps-dir "${steps_td}" \
        --oj-source-provided 0 \
        >/dev/null 2>"${stderr_log}" || exit_code=$?

    local stderr_text
    stderr_text=$(cat "${stderr_log}")

    local errors=""
    # Check c violation should NOT contain "F16-architecture" — that
    # would indicate the [FILE: ...] marker leaked into the canonical-id
    # closure scan.
    if printf '%s' "${stderr_text}" | grep -E "canonical-id-orphan.*F16-architecture" >/dev/null 2>&1; then
        errors="${errors}    Check c surfaced canonical-id-orphan for the [FILE: ...] marker"$'\n'
    fi
    if [ -z "${errors}" ]; then
        echo -e "${GREEN}PASS${NC} positive/file-marker (planted [FILE: F16-architecture.md] did NOT fire canonical-id-orphan)"
        PASS_COUNT=$((PASS_COUNT + 1))
    else
        echo -e "${RED}FAIL${NC} positive/file-marker"
        printf '%s' "${errors}"
        echo -e "${CYAN}    actual exit=${exit_code}${NC}"
        echo -e "${CYAN}    actual stderr (head -40):${NC}"
        printf '%s\n' "${stderr_text}" | head -40 | sed 's/^/      /'
        FAIL_COUNT=$((FAIL_COUNT + 1))
    fi

    rm -rf "${steps_td}" "${prompt_td}" "${stderr_log}"
}

echo -e "${YELLOW}[INFO]${NC} BL-025-h validate-dry-run Check c regression test"
echo -e "${YELLOW}[INFO]${NC} validator: ${VALIDATE}"
echo -e "${YELLOW}[INFO]${NC} spec dir:  ${SPEC_DIR}"
echo

run_negative_scenario
run_positive_scenario
run_positive_file_marker_scenario

echo
echo "================================"
TOTAL=$((PASS_COUNT + FAIL_COUNT))
if [ "${FAIL_COUNT}" -eq 0 ]; then
    echo -e "${GREEN}PASS${NC} canonical-id closure: ${PASS_COUNT}/${TOTAL}"
    echo "================================"
    exit 0
else
    echo -e "${RED}FAIL${NC} canonical-id closure: ${FAIL_COUNT}/${TOTAL} scenario(s) failed"
    echo "================================"
    exit 1
fi
